<?php

namespace Database\Seeders;

use App\Models\Stock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stocks = [
            [
                'symbol' => 'AAPL',
                'name' => 'Apple Inc.',
                'description' => 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.',
                'sector' => 'Technology',
                'industry' => 'Consumer Electronics',
                'current_price' => 178.50,
                'opening_price' => 177.25,
                'previous_close' => 177.80,
                'day_high' => 179.20,
                'day_low' => 176.90,
                'volume' => 52847100,
                'market_cap' => 2780000000000,
                'pe_ratio' => 29.5,
                'dividend_yield' => 0.0051,
                'is_active' => true,
            ],
            [
                'symbol' => 'MSFT',
                'name' => 'Microsoft Corporation',
                'description' => 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide.',
                'sector' => 'Technology',
                'industry' => 'Software',
                'current_price' => 378.90,
                'opening_price' => 376.50,
                'previous_close' => 377.20,
                'day_high' => 380.10,
                'day_low' => 375.80,
                'volume' => 21456300,
                'market_cap' => 2810000000000,
                'pe_ratio' => 35.2,
                'dividend_yield' => 0.0075,
                'is_active' => true,
            ],
            [
                'symbol' => 'GOOGL',
                'name' => 'Alphabet Inc.',
                'description' => 'Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America.',
                'sector' => 'Technology',
                'industry' => 'Internet Content & Information',
                'current_price' => 142.65,
                'opening_price' => 141.30,
                'previous_close' => 141.80,
                'day_high' => 143.20,
                'day_low' => 140.90,
                'volume' => 18923400,
                'market_cap' => 1800000000000,
                'pe_ratio' => 25.8,
                'dividend_yield' => 0.0000,
                'is_active' => true,
            ],
            [
                'symbol' => 'AMZN',
                'name' => 'Amazon.com Inc.',
                'description' => 'Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally.',
                'sector' => 'Consumer Cyclical',
                'industry' => 'Internet Retail',
                'current_price' => 178.25,
                'opening_price' => 176.80,
                'previous_close' => 177.50,
                'day_high' => 179.40,
                'day_low' => 176.20,
                'volume' => 34567800,
                'market_cap' => 1850000000000,
                'pe_ratio' => 62.3,
                'dividend_yield' => 0.0000,
                'is_active' => true,
            ],
            [
                'symbol' => 'TSLA',
                'name' => 'Tesla Inc.',
                'description' => 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.',
                'sector' => 'Consumer Cyclical',
                'industry' => 'Auto Manufacturers',
                'current_price' => 248.50,
                'opening_price' => 245.30,
                'previous_close' => 246.80,
                'day_high' => 251.20,
                'day_low' => 244.60,
                'volume' => 98765400,
                'market_cap' => 789000000000,
                'pe_ratio' => 72.1,
                'dividend_yield' => 0.0000,
                'is_active' => true,
            ],
            [
                'symbol' => 'NVDA',
                'name' => 'NVIDIA Corporation',
                'description' => 'NVIDIA Corporation provides graphics, and compute and networking solutions in the United States, Taiwan, China, and internationally.',
                'sector' => 'Technology',
                'industry' => 'Semiconductors',
                'current_price' => 485.60,
                'opening_price' => 480.20,
                'previous_close' => 482.90,
                'day_high' => 488.70,
                'day_low' => 479.30,
                'volume' => 45678900,
                'market_cap' => 1200000000000,
                'pe_ratio' => 68.5,
                'dividend_yield' => 0.0003,
                'is_active' => true,
            ],
            [
                'symbol' => 'JPM',
                'name' => 'JPMorgan Chase & Co.',
                'description' => 'JPMorgan Chase & Co. operates as a financial services company worldwide.',
                'sector' => 'Financial Services',
                'industry' => 'Banks',
                'current_price' => 195.40,
                'opening_price' => 194.10,
                'previous_close' => 194.80,
                'day_high' => 196.20,
                'day_low' => 193.50,
                'volume' => 8765400,
                'market_cap' => 567000000000,
                'pe_ratio' => 11.2,
                'dividend_yield' => 0.0225,
                'is_active' => true,
            ],
            [
                'symbol' => 'JNJ',
                'name' => 'Johnson & Johnson',
                'description' => 'Johnson & Johnson researches, develops, manufactures, and sells various products in the healthcare field worldwide.',
                'sector' => 'Healthcare',
                'industry' => 'Drug Manufacturers',
                'current_price' => 156.80,
                'opening_price' => 155.90,
                'previous_close' => 156.20,
                'day_high' => 157.40,
                'day_low' => 155.60,
                'volume' => 6543200,
                'market_cap' => 378000000000,
                'pe_ratio' => 24.3,
                'dividend_yield' => 0.0295,
                'is_active' => true,
            ],
            [
                'symbol' => 'V',
                'name' => 'Visa Inc.',
                'description' => 'Visa Inc. operates as a payments technology company worldwide.',
                'sector' => 'Financial Services',
                'industry' => 'Credit Services',
                'current_price' => 279.30,
                'opening_price' => 277.80,
                'previous_close' => 278.50,
                'day_high' => 280.10,
                'day_low' => 277.20,
                'volume' => 5432100,
                'market_cap' => 567000000000,
                'pe_ratio' => 30.8,
                'dividend_yield' => 0.0075,
                'is_active' => true,
            ],
            [
                'symbol' => 'WMT',
                'name' => 'Walmart Inc.',
                'description' => 'Walmart Inc. engages in the operation of retail, wholesale, and other units worldwide.',
                'sector' => 'Consumer Defensive',
                'industry' => 'Discount Stores',
                'current_price' => 165.20,
                'opening_price' => 164.30,
                'previous_close' => 164.80,
                'day_high' => 165.90,
                'day_low' => 163.80,
                'volume' => 7654300,
                'market_cap' => 445000000000,
                'pe_ratio' => 28.5,
                'dividend_yield' => 0.0125,
                'is_active' => true,
            ],
            [
                'symbol' => 'DIS',
                'name' => 'The Walt Disney Company',
                'description' => 'The Walt Disney Company operates as an entertainment company worldwide.',
                'sector' => 'Communication Services',
                'industry' => 'Entertainment',
                'current_price' => 112.40,
                'opening_price' => 111.20,
                'previous_close' => 111.80,
                'day_high' => 113.10,
                'day_low' => 110.90,
                'volume' => 9876500,
                'market_cap' => 205000000000,
                'pe_ratio' => 72.5,
                'dividend_yield' => 0.0000,
                'is_active' => true,
            ],
            [
                'symbol' => 'NFLX',
                'name' => 'Netflix Inc.',
                'description' => 'Netflix, Inc. provides entertainment services. It offers TV series, documentaries, feature films, and mobile games across various genres and languages.',
                'sector' => 'Communication Services',
                'industry' => 'Entertainment',
                'current_price' => 445.80,
                'opening_price' => 442.30,
                'previous_close' => 443.90,
                'day_high' => 448.20,
                'day_low' => 441.50,
                'volume' => 3456700,
                'market_cap' => 198000000000,
                'pe_ratio' => 42.3,
                'dividend_yield' => 0.0000,
                'is_active' => true,
            ],
        ];

        foreach ($stocks as $stock) {
            Stock::create($stock);
        }
    }
}